title: Blackndsky.net
description: >- # this means to ignore newlines until "baseurl:"
  Windows - Linux - Powershell
baseurl: "/"
url: "https://blackndsky.net"
theme: jekyll-theme-midnight
exclude: 
   - README.md
   - Gemfile
   - Gemfile.lock
   - CNAME

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
